-- Create Flashcards Table
CREATE TABLE flashcards (
  id bigint generated by default as identity primary key,
  sdg_number integer not null, -- Usage of sdg_number instead of id for easier seeding
  front_text text not null,
  icon_name text not null, -- Lucide icon name
  back_text text not null,
  color_theme text default 'bg-blue-500' -- Tailwind class for back color or border
);

-- Seed Data for SDG 13 (Climate Action)
INSERT INTO flashcards (sdg_number, front_text, icon_name, back_text, color_theme) VALUES
(13, 'Carbon Footprint', 'Footprints', 'The total amount of greenhouse gases generated by our actions.', 'bg-green-500'),
(13, 'Renewable Energy', 'Sun', 'Energy from sources that never run out, like wind and solar.', 'bg-yellow-500'),
(13, 'Greenhouse Effect', 'CloudFog', 'Gases trapping heat in the atmosphere, keeping Earth warm.', 'bg-red-500'),
(13, 'Deforestation', 'Axe', 'The clearing of forests, which removes carbon sinks.', 'bg-amber-700'),
(13, 'Sustainability', 'Recycle', 'Meeting our needs without harming future generations.', 'bg-emerald-600');

-- Seed Data for SDG 14 (Life Below Water) - Using 14 instead of 7 as user asked for active quests
INSERT INTO flashcards (sdg_number, front_text, icon_name, back_text, color_theme) VALUES
(14, 'Coral Bleaching', 'Shell', 'When corals lose their colors due to stressed warm water.', 'bg-rose-400'),
(14, 'Microplastics', 'Trash2', 'Tiny plastic particles that pollute oceans and harm sea life.', 'bg-purple-500'),
(14, 'Overfishing', 'FishOff', 'Catching fish faster than stocks can replenish.', 'bg-blue-600'),
(14, 'Ocean Acidification', 'TestTube', 'The ocean becoming more acidic due to absorbing CO2.', 'bg-teal-500'),
(14, 'Marine Protected Area', 'Shield', 'A zone where ocean life is protected from human activity.', 'bg-indigo-500');

-- Seed Data for SDG 4 (Quality Education)
INSERT INTO flashcards (sdg_number, front_text, icon_name, back_text, color_theme) VALUES
(4, 'Literacy', 'BookOpen', 'The ability to read and write, a foundation for learning.', 'bg-orange-500'),
(4, 'Lifelong Learning', 'Infinity', 'Pursuing knowledge throughout your entire life.', 'bg-pink-500'),
(4, 'Inclusive Education', 'Users', 'Ensuring everyone can learn, regardless of ability or background.', 'bg-cyan-500'),
(4, 'STEM', 'Microscope', 'Science, Technology, Engineering, and Mathematics.', 'bg-violet-500'),
(4, 'Scholarship', 'GraduationCap', 'Financial aid to support a student''s education.', 'bg-yellow-600');

-- Enable RLS
ALTER TABLE flashcards ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public flashcards are viewable by everyone" ON flashcards FOR SELECT USING ( true );
