-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Profiles table
create table profiles (
  id uuid references auth.users not null primary key,
  username text unique,
  xp integer default 0,
  coins integer default 0, -- Currency for shop
  streak_count integer default 0,
  last_active_at timestamp with time zone default now(),
  unlocked_avatars text[] default array[]::text[], -- Seeds of unlocked avatars
  avatar_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Quests table
create table quests (
  id bigint generated by default as identity primary key,
  sdg_number integer not null,
  title text not null,
  description text,
  bg_gradient_color text, -- CSS gradient string e.g., "from-green-400 to-blue-500"
  icon text, -- Lucide icon name or URL
  type text check (type in ('quiz', 'action')) default 'quiz'
);

-- Questions table (Used for Quiz type)
create table questions (
  id bigint generated by default as identity primary key,
  quest_id bigint references quests not null,
  question_text text not null,
  options text[] not null, -- Array of 4 options
  correct_answer_index integer not null, -- 0-3
  explanation text
);

-- Achievements table
create table achievements (
  id text primary key, -- slug e.g. 'first-quest'
  title text not null,
  description text not null,
  icon text not null, -- Lucide icon name
  xp_reward integer default 0
);

-- User Achievements table
create table user_achievements (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) not null,
  achievement_id text references achievements(id) not null,
  unlocked_at timestamp with time zone default timezone('utc'::text, now()) not null
);


-- User Progress table
create table user_progress (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) not null,
  quest_id bigint references quests(id) not null,
  score integer not null,
  completed_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Trigger for new user profile
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, username, avatar_url)
  values (new.id, new.raw_user_meta_data->>'username', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
