-- SDG 13: Climate Action
INSERT INTO public.quests (sdg_number, title, description, bg_gradient_color, icon)
VALUES 
(13, 'Climate Action Hero', 'Take urgent action to combat climate change and its impacts. Learn how you can make a difference!', 'from-green-500 to-emerald-700', 'leaf');

-- Questions for SDG 13
INSERT INTO public.questions (quest_id, question_text, options, correct_answer_index, explanation)
VALUES
((SELECT id FROM public.quests WHERE sdg_number = 13), 'Which of these gases is most responsible for global warming?', ARRAY['Oxygen', 'Carbon Dioxide (CO2)', 'Nitrogen', 'Helium'], 1, 'Carbon Dioxide traps heat in the atmosphere, acting like a blanket and warming the planet.'),
((SELECT id FROM public.quests WHERE sdg_number = 13), 'What is a renewable energy source?', ARRAY['Coal', 'Oil', 'Solar Power', 'Natural Gas'], 2, 'Solar power comes from the sun and never runs out, unlike fossil fuels that pollute.'),
((SELECT id FROM public.quests WHERE sdg_number = 13), 'What can you do to help reduced carbon footprints?', ARRAY['Leave lights on', 'Drive everywhere', 'Plant trees', 'Use more plastic'], 2, 'Trees absorb CO2 and release oxygen, helping to clean the air and cool the planet!'),
((SELECT id FROM public.quests WHERE sdg_number = 13), 'What is the main goal of the Paris Agreement?', ARRAY['Mars Exploration', 'Limit global warming to 1.5°C', 'Build more factories', 'Print more money'], 1, 'The Paris Agreement aims to limit global temperature rise to well below 2°C, preferably to 1.5°C.'),
((SELECT id FROM public.quests WHERE sdg_number = 13), 'What is "The Greenhouse Effect"?', ARRAY['Building greenhouses', 'Gases trapping heat in Earth''s atmosphere', 'Painting houses green', 'Plants growing faster'], 1, 'It is the process where gases like CO2 trap the Sun''s heat, keeping Earth warm enough for life but dangerous in excess.'),
((SELECT id FROM public.quests WHERE sdg_number = 13), 'Which of these activities produces the most carbon emissions?', ARRAY['Walking', 'Cycling', 'Flying in an airplane', 'Sleeping'], 2, 'Air travel burns large amounts of fossil fuels at high altitudes, contributing significantly to emissions.'),
((SELECT id FROM public.quests WHERE sdg_number = 13), 'What effect does climate change have on sea levels?', ARRAY['They rise', 'They fall', 'They stay the same', 'They turn into jelly'], 0, 'Melting ice caps and thermal expansion of water cause sea levels to rise, threatening coastal cities.'),
((SELECT id FROM public.quests WHERE sdg_number = 13), 'What is a "carbon footprint"?', ARRAY['A footprint in coal', 'The total greenhouse gases we produce', 'A new shoe brand', 'Carbon dating'], 1, 'Your carbon footprint is the total amount of greenhouse gases (including CO2) that are generated by your actions.'),
((SELECT id FROM public.quests WHERE sdg_number = 13), 'Which of these is a fossil fuel?', ARRAY['Wind', 'Sunlight', 'Coal', 'Water'], 2, 'Coal, oil, and natural gas are fossil fuels formed from ancient remains, and burning them releases CO2.'),
((SELECT id FROM public.quests WHERE sdg_number = 13), 'How does recycling help climate change?', ARRAY['It uses more energy', 'It reduces waste and energy needed for new materials', 'It makes trash smell better', 'It does nothing'], 1, 'Recycling reduces the need to extract and process new raw materials, saving energy and reducing emissions.');

-- SDG 14: Life Below Water
INSERT INTO public.quests (sdg_number, title, description, bg_gradient_color, icon)
VALUES 
(14, 'Ocean Guardian', 'Conserve and sustainably use the oceans, seas and marine resources.', 'from-blue-400 to-cyan-600', 'droplets');

-- Questions for SDG 14
INSERT INTO public.questions (quest_id, question_text, options, correct_answer_index, explanation)
VALUES
((SELECT id FROM public.quests WHERE sdg_number = 14), 'What is the largest animal in the ocean?', ARRAY['Great White Shark', 'Blue Whale', 'Giant Squid', 'Orca'], 1, 'The Blue Whale is the largest animal known to have ever lived, even bigger than dinosaurs!'),
((SELECT id FROM public.quests WHERE sdg_number = 14), 'Why are coral reefs important?', ARRAY['They look pretty', 'They are homes for many fish', 'They make the water blue', 'They are just rocks'], 1, 'Coral reefs provide shelter and food for 25% of all marine life!'),
((SELECT id FROM public.quests WHERE sdg_number = 14), 'What causes "ocean acidification"?', ARRAY['Too much salt', 'Fish peeing', 'Absorption of CO2', 'Sunlight'], 2, 'The ocean absorbs CO2 from the air, which makes the water more acidic and harms sea life.'),
((SELECT id FROM public.quests WHERE sdg_number = 14), 'How much of Earth''s surface is covered by ocean?', ARRAY['10%', '50%', '71%', '90%'], 2, 'The ocean covers more than 70% of our planet''s surface!'),
((SELECT id FROM public.quests WHERE sdg_number = 14), 'What makes up the "Great Pacific Garbage Patch"?', ARRAY['Islands', 'Plastic waste', 'Seaweed', 'Boats'], 1, 'It is a massive collection of marine debris, mostly floating plastics, in the North Pacific Ocean.'),
((SELECT id FROM public.quests WHERE sdg_number = 14), 'How does plastic harm sea turtles?', ARRAY['It looks like jellyfish', 'It makes them float', 'It tangles them', 'All of the above'], 3, 'Turtles often eat plastic bags mistaking them for jellyfish, and can also get entangled in discarded nets.'),
((SELECT id FROM public.quests WHERE sdg_number = 14), 'What is "overfishing"?', ARRAY['Fishing from a tall boat', 'Catching fish faster than they can reproduce', 'Fishing at night', 'Eating too much fish'], 1, 'Overfishing depletes fish stocks, disrupting the marine food web and threatening the livelihoods of coastal communities.'),
((SELECT id FROM public.quests WHERE sdg_number = 14), 'What percentage of the air we breathe comes from the ocean?', ARRAY['None', 'Over 50%', '10%', '100%'], 1, 'Marine plants, specifically phytoplankton, produce over half of the world''s oxygen!'),
((SELECT id FROM public.quests WHERE sdg_number = 14), 'Which of these is NOT a marine mammal?', ARRAY['Dolphin', 'Whale', 'Seal', 'Shark'], 3, 'Sharks are fish because they breathe using gills, unlike mammals which breathe air.'),
((SELECT id FROM public.quests WHERE sdg_number = 14), 'What is a Marine Protected Area (MPA)?', ARRAY['An ocean zoo', 'A zone where human activity is limited for conservation', 'A beach for swimming', 'A submarine base'], 1, 'MPAs are sections of the ocean where government has placed limits on human activity to protect the marine environment.');

-- SDG 4: Quality Education
INSERT INTO public.quests (sdg_number, title, description, bg_gradient_color, icon)
VALUES 
(4, 'Education for All', 'Ensure inclusive and equitable quality education and promote lifelong learning opportunities for all.', 'from-red-400 to-rose-600', 'star');

-- Questions for SDG 4
INSERT INTO public.questions (quest_id, question_text, options, correct_answer_index, explanation)
VALUES
((SELECT id FROM public.quests WHERE sdg_number = 4), 'Why is education important?', ARRAY['To get rich', 'To escape chores', 'To empower people and improve lives', 'To memorize facts'], 2, 'Education gives people the skills they need to stay healthy, get jobs, and contribute to society.'),
((SELECT id FROM public.quests WHERE sdg_number = 4), 'What is a barrier to education for some kids?', ARRAY['Too many books', 'Distance to school', 'Free lunch', 'Nice teachers'], 1, 'Many children live too far from the nearest school and have no way to get there.'),
((SELECT id FROM public.quests WHERE sdg_number = 4), 'What does "literacy" mean?', ARRAY['Ability to run fast', 'Ability to read and write', 'Ability to cook', 'Ability to drive'], 1, 'Literacy is the foundational ability to read and write, crucial for learning and communication.'),
((SELECT id FROM public.quests WHERE sdg_number = 4), 'Which group often faces more barriers to attending school?', ARRAY['Boys', 'Girls', 'Tall people', 'Gamers'], 1, 'In many parts of the world, girls are less likely to be sent to school due to cultural norms or poverty.'),
((SELECT id FROM public.quests WHERE sdg_number = 4), 'What is "lifelong learning"?', ARRAY['Learning only as a child', 'Learning only at university', 'Continuing to learn throughout your entire life', 'Studying 24 hours a day'], 2, 'It means that education isn''t just for kids; we can keep gaining skills and knowledge at any age!'),
((SELECT id FROM public.quests WHERE sdg_number = 4), 'Roughly how many children and youth are out of school globally?', ARRAY['Zero', '1000', 'Over 250 million', '100 million'], 2, 'According to UNESCO, over 250 million children and youth are not in school.'),
((SELECT id FROM public.quests WHERE sdg_number = 4), 'How does education improve health?', ARRAY['It doesn''t', 'Educated people can read medicine labels and learn hygiene', 'School lunches are magic', 'Homework acts as exercise'], 1, 'Education provides knowledge about nutrition, hygiene, and disease prevention.'),
((SELECT id FROM public.quests WHERE sdg_number = 4), 'What is needed for a quality education?', ARRAY['Safe schools and trained teachers', 'Expensive uniforms', 'Gold pencils', 'Video games'], 0, 'A safe environment and qualified teachers are essential for effective learning.'),
((SELECT id FROM public.quests WHERE sdg_number = 4), 'What is a "scholarship"?', ARRAY['A boat', 'Financial aid to help pay for education', 'A school bus', 'A type of pencil'], 1, 'Scholarships help students pay for school who might otherwise not be able to afford it.'),
((SELECT id FROM public.quests WHERE sdg_number = 4), 'How can you help others get an education?', ARRAY['Hide their books', 'Donate books or tutor someone', 'Sleep in class', 'Skip school'], 1, 'Sharing resources and knowledge is a great way to support SDG 4!');

-- SDG 15: Life on Land (Action Quest)
INSERT INTO public.quests (sdg_number, title, description, bg_gradient_color, icon, type)
VALUES 
(15, 'Plant a Tree', 'Trees are the lungs of our planet. Go out and plant one (or a digital one) to help the earth breathe!', 'from-green-600 to-lime-500', 'sprout', 'action');

-- Achievements Seed
INSERT INTO public.achievements (id, title, description, icon, xp_reward)
VALUES
('first_step', 'First Step', 'Complete your first quest', 'footprints', 50),
('climate_hero', 'Climate Hero', 'Complete a Climate Action quest', 'sun', 100),
('ocean_defender', 'Ocean Defender', 'Complete an Ocean quest', 'anchor', 100),
('level_10', 'Rising Star', 'Reach 100 XP', 'star', 0);
